sudo: false
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
branches:
  except:
    - /^WIP-.*$/
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
# virtualenv>=14.0.0 is incompatible with python 3.2 (which is also what pypy3
# currently provides)
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' || $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then travis_retry pip install tox "virtualenv<14.0.0" ; else pip install -U tox virtualenv; fi
script:
  - tox -e py${TRAVIS_PYTHON_VERSION}
